var podDescriptions = {
   reveal: "Dispatches from the Center of Investigative Reporting and PRX."
   nypl: "Interviews recorded live at the New York Public Library."
   in-our-time: "Panel discussions about big ideas from BBC Radio 4."
   open-source: "Smart talk on arts and politics from WBUR."
   radiolab: "Adventures in science and philosophy from WNYC."
   radiotonic: "Documentaries about the humanities from ABC."
   factmag: "Music mixes from leading DJs and composers."
   homebrave: "Mini documentaries from Scott Carrier."
   rumble: "Conversations with interesting Vermonters."
   ideas: "Documentaries about social issues from the CBC."
   unfictional: "Features by independent producers from KCRW."
   organist: "Experimental stories from The Believer and KCRW."
   shortcuts: "Small themed stories from BBC Radio 4."
   seriously: "Quirky documentaries from BBC Radio 4."
   bodegaboys: "Hilarious takes on pop culture from Red Bull Studios."
   snapjudgement: "Beat-backed stories from WNYC."
   worldinwords: "Explorations of language from WGBH."
   chapos-traphouse: "Irreverent left-wing comedy."
}
 
