var podDescriptions = {
   "reveal": "Dispatches from the Center of Investigative Reporting and PRX.",
   "nypl": "Interviews recorded live at the New York Public Library.",
   "in-our-time": "Panel discussions about big ideas from BBC Radio 4.",
   "open-source": "Smart talk on arts and politics from WBUR.",
   "radiolab": "Adventures in science and philosophy from WNYC.",
   "radiotonic": "Documentaries about the humanities from ABC.",
   "factmag": "Music mixes from leading DJs and composers.",
   "homebrave": "Mini documentaries from Scott Carrier.",
   "rumble": "Conversations with interesting Vermonters.",
   "ideas": "Documentaries about social issues from the CBC.",
   "unfictional": "Features by independent producers from KCRW.",
   "organist": "Experimental stories from The Believer and KCRW.",
   "shortcuts": "Small themed stories from BBC Radio 4.",
   "seriously": "Quirky documentaries from BBC Radio 4.",
   "bodegaboys": "Funny takes on pop culture from Red Bull Studios.",
   "snapjudgement": "Stories with a beat from WNYC.",
   "worldinwords": "Explorations of language from WGBH.",
   "chapos-traphouse": "Irreverent left-wing comedy.",
   "desert-island-discs" : "Interviews about music for all time from BBC Radio 4.",
   "guardian": "Longform articles from The Guardian.",
   "grey-wolf-feed": "Delicious bonus content from Crapo Fash House.",
   "ben-dixon-show": "Progressive political analysis.",
   "eternal-now": "WFMU DJ Andy Ortmann explores obscure music.",
   "london-review": "Readings and discussions from the LRB.",
   "honky-tonk": "Twangs of all stripes. From WFMU.",
   "resident-advisor": "Music mixes from top producers.",
   "mouth-time": "Satirical women's lifestyle podcast from Reductress.",
   "call-chelsea-peretti": "Bizarre call-in comedy show."
};
