var podDescriptions = {
   "reveal": "Dispatches from the Center of Investigative Reporting and PRX.",
   "in-our-time": "Panel talks about big ideas from BBC Radio 4.",
   "open-source": "Smart talk on arts and politics from WBUR.",
   "homebrave": "Mini documentaries from Scott Carrier.",
   "rumble": "Conversations with interesting Vermonters.",
   "unfictional": "Features by independent producers from KCRW.",
   "organist": "Experimental stories from The Believer and KCRW.",
   "shortcuts": "Small themed stories from BBC Radio 4.",
   "seriously": "Quirky documentaries from BBC Radio 4.",
   "bodegaboys": "Funny takes on pop culture from Red Bull Studios.",
   "snapjudgement": "Stories with a beat from WNYC.",
   "chapos-traphouse": "Irreverent left-wing comedy.",
   "desert-island-discs" : "Interviews about music for all time from BBC Radio 4.",
   "guardian": "Longform articles from The Guardian.",
   "eternal-now": "WFMU DJ Andy Ortmann explores obscure music.",
   "london-review": "Readings and discussions from the LRB.",
   "honky-tonk": "Twangs of all stripes. From WFMU.",
   "resident-advisor": "Music mixes from top producers.",
   "mouth-time": "Satirical lifestyle show from Reductress.",
   "intercept": "News and analysis from The Intercept's reporters.",
   "between-the-ears": "BBC Radio 3's long-running experimental sound program.",
   "the-essay": "Public intellectuals give insight into the arts.",
   "fishko-files": "Features from WNYC culture reporter Sara Fishko.",
   "bird-note": "Your regular dose of avian soundscapes.",
   "upstream": "Stories that challenge traditional economics.",
   "moderate-rebels": "Anti-imperialism from Ben Norton and Max Blumenthal.",
   "delete-your-acct": "Roqayah Chamseddine and Kumars Salehi chat politics.",
   "citations": "Nima Shirazi and Adam Johnson chat media and power.",
   "by-any-means-necessary": "News and analysis from radical Eugene Puryear.",
   "kt-halps": "A humorous look at news and arts from WBAI.",
   "discoursecollective": "Communist teens discuss theory and culture.",
   "street-fight": "The No. 1 Anarcho-comedy Radio Show.",
   "doomscroll": "Explores online culture and politics in the 21st century.",
   "turbulence": "A podcast about the end of the American empire, or the end of the world—whichever comes first."
};
