var streams = [ { title: 'WMBR',
    description: 'Music and public affairs out of MIT in Cambridge.',
    url: 'http://wmbr.org/',
    donateurl: 'https://wmbr.org/fundraising.php',
    streamurl: 'http://headphones.mit.edu:8000/hi' },
  { title: 'Berlin Community Radio',
    description: 'An electronic music internet station.',
    url: 'http://www.berlincommunityradio.com',
    donateurl: 'http://www.berlincommunityradio.com/donate-berlin-community-radio',
    streamurl: 'http://berlincommunityradio.out.airtime.pro:8000/berlincommunityradio_a' },
  { title: 'WFMU',
    description: 'New York\'s weirdest and best freeform station.',
    url: 'https://wfmu.org/',
    donateurl: 'https://wfmu.org/marathon-2016/',
    streamurl: 'http://stream0.wfmu.org/freeform-128k' },
  { title: 'WWOZ',
    description: 'Jazz and more out of New Orleans.',
    url: 'http://www.wwoz.org/',
    donateurl: 'http://www.wwoz.org/donate.php',
    streamurl: 'http://wwoz-sc.streamguys.com:80/wwoz-hi.mp3' },
  { title: 'Resonance FM',
    description: 'London\'s groundbreaking art radio station.',
    url: 'https://resonancefm.com/',
    donateurl: 'https://resonancefm.com/donate',
    streamurl: 'http://54.77.136.103:8000/resonance' },
  { title: 'WERU',
    description: 'Midcoast Maine\'s voice of many voices.',
    url: 'https://weru.org/',
    donateurl: 'https://weru.org/donate',
    streamurl: 'http://stream.weru.org/weru-high.mp3' },
  { title: 'WXYC',
    description: 'Student radio from Chapel Hill, North Carolina.',
    url: 'http://www.wxyc.org/',
    donateurl: 'http://www.wxyc.org/merch',
    streamurl: 'http://audio-mp3.ibiblio.org:8000/wxyc.mp3' },
  { title: 'BBC Radio 3',
    description: 'New and classical music.',
    url: 'http://www.bbc.co.uk/radio3',
    donateurl: null,
    streamurl: 'http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio3_mf_p?s=1454876177&e=1454890577&h=e1f6b6a5fcb3ca60b131bbdfcb02f980' },
  { title: 'BBC Radio 4',
    description: 'Documentaries and spoken word programs.',
    url: 'http://www.bbc.co.uk/radio4',
    donateurl: null,
    streamurl: 'http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio4fm_mf_q' },
  { title: 'BBC Radio 6',
    description: 'BBC\'s alternative music station.',
    url: 'http://www.bbc.co.uk/6music',
    donateurl: null,
    streamurl: 'http://bbcmedia.ic.llnwd.net/stream/bbcmedia_6music_mf_p' },
  { title: 'WMPG',
    description: 'Portland, Maine community radio.',
    url: 'http://www.wmpg.org/',
    donateurl: 'http://www.wmpg.org/support-wmpg/listener-donations/',
    streamurl: 'http://quarrel.str3am.com:7270/;stream.mp3' },
  { title: 'Terry Radio',
    description: '90.5 KGHI\'s sounds are electronic and experimental.',
    url: 'http://www.terryradio.biz/',
    donateurl: null,
    streamurl: 'http://terryradio.dtdns.net:8000/terry1' },
  { title: 'WUMB',
    description: 'Folk and more out of UMass Boston.',
    url: 'http://www.wumb.org/home/index.php',
    donateurl: 'http://www.wumb.org/members/donate/',
    streamurl: 'http://wumb.streamguys1.com/wumb919fast' },
  { title: 'WNUR',
    description: 'Chicago\'s sound experiment.',
    url: 'https://www.wnur.org/',
    donateurl: 'http://wewill.northwestern.edu/supportwnur',
    streamurl: 'http://sc1.spacialnet.com:32660/;wnur.mp3' },
  { title: 'Wave Farm Radio',
    description: 'Transmission art out of Hudson, New York.',
    url: 'https://wavefarm.org/',
    donateurl: 'https://wavefarm.org/wgxc/donate',
    streamurl: 'http://comm.free103point9.org:8000/transmissionarts.mp3' },
  { title: 'WKCR',
    description: 'The Original FM specializing in jazz, classical, and roots music.',
    url: 'https://www.wkcr.org',
    donateurl: 'https://giving.columbia.edu/giveonline/?schoolstyle=411',
    streamurl: 'http://wkcr.streamguys1.com:80/live' },
  { title: 'Bondfire Radio',
    description: 'Brooklyn\'s real radio for real people.',
    url: 'http://bondfireradio.com/',
    donateurl: 'https://www.patreon.com/bondfireradio',
    streamurl: 'https://streaming.radio.co/sd2fdc24b0/listen' }
]
